.DEFAULT_GOAL := deploy_linux

deploy_linux:
	install_linux /app/cmd/editor

deploy_js:
	deploy_js /app/cmd/editor

deploy_wasm:
	deploy_wasm /app/cmd/editor

clean:
	rm -rf deploy linux js wasm rcc*
